version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config-server:
    build: microservices/config-server
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry-server:
    build: microservices/registry-server
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway-server:
    build: microservices/gateway-server
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  product-microservice:
    environment:
      MONGODB_PASSWORD: password123
    build: microservices/product-microservice
    depends_on:
      config-server:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  product-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: password123
    build: data-stores/mongodb
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring-server:
      build: microservices/monitoring-server
      depends_on:
        config-server:
          condition: service_healthy
      ports:
        - 9000:8080
        - 8989:8989
      logging:
        options:
          max-size: "10m"
          max-file: "10"