version: '2.1'

services:
  rabbitmq:
    ports:
      - 5672:5672

  config-server:
    build: microservices/config-server
    ports:
      - 8888:8888

  registry-server:
    build: microservices/registry-server

  gateway-server:
    build: microservices/gateway-server

  product-microservice:
    build: microservices/product-microservice
    ports:
      - 8000:8000

  product-mongodb:
    build: data-stores/mongodb
    ports:
      - 26000:27017

  monitoring-server:
        build: microservices/monitoring-server
