version: '2.1'

services:
  rabbitmq:
    restart: always
    ports:
      - 5672:5672

  config:
    build: microservices/config-server
    ports:
      - 8888:8888

  registry-server:
    build: microservices/registry-server

  gateway-server:
    build: microservices/gateway-server

  product-microservice:
    build: microservices/product-microservice
    ports:
      - 5000:5000

  auth-mongodb:
    build: data-stores/mongodb
    ports:
      - 25000:27017

  monitoring-server:
    build: microservices/monitoring-server
