logging:
  level:
    org.springframework: INFO

spring:
  application:
      name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sepulrator/ecommerce-platform-config-repo

server:
  port: 8888

management:
  security:
    enabled: false

security:
  basic:
    enabled: false


